### PR TITLE
Added citation.cff file

### PR DESCRIPTION
**Pull request by NixImagery**
The cff file provides a simple way for users of the template to cite it in their own thesis. It's only good manners.

### CODE REVIEW

**Comment by NixImagery** [comment]
oh, and thanks for the template, by the way. It's really easy to use with quarto/markdown.

**Comment by H0R5E** [comment]
Thanks! I'd never heard of Quarto, but I am a Pandoc user. Have you turned the template into a Pandoc template to use with Quarto? I'd be interested to see/host that.

**Comment by NixImagery** [comment]
Hi Matthew -- I've made a [template repo](https://github.com/NixImagery/edengths-quarto/) based on a fork of yours so folks can quickly set up a quarto site/thesis using markdown. There's a [gh-pages site](https://niximagery.github.io/edengths-quarto/) that shows the output. It uses `edengths.cls`, `packages.tex` and `edengfmt.tex` from your repo. What do you think? I don't think it (should) merge with yours but if you can see a way of making it useful then go ahead.

**Comment by H0R5E** [comment]
Thanks! It's interesting to see, for sure. I will most likely add a link to the README so that folks can have a look at your fork.

**Pull request merged**
